---
title: "Stat380MiniProject3"
output: html_document
author: "Jeffery Yue and Ben Howland"
date: "04/28/25"
---

## Front Matter
```{r}
remove(list = ls())
library(tidyverse)
library(readxl)
library(glmnet)
COD <- read_excel("CODGames2_mp.xlsx")
```


## Problem 1
```{r}
COD2 = COD %>% 
  filter(FullPartial == "Full")
ggplot(data = COD2, mapping = aes(x = XPType, y = TotalXP))+geom_boxplot()+labs(x = "XP Type", y = "Total XP")
```
```{r}
summary = COD2 %>% group_by(XPType) %>% summarise(Min = min(TotalXP), Max = max(TotalXP), Mean = mean(TotalXP), Median = median(TotalXP), StdDev = sd(TotalXP))
print(summary)
```
The games with Double XP tend to have much higher total XP values than the games with just the 10% boost. The double XP games also have a higher standard deviation and more outliers indicating more variation. 


## Problem 2

```{r}
#Code to determine if a player won that specific game
Splitresult = str_split_fixed(COD2$Result, "-", 2)
colnames(Splitresult) = c("Team", "Opponent")
Splitresult2 = data.frame(Splitresult)
Team = as.numeric(unlist(Splitresult2$Team))
Opponent = as.numeric(unlist(Splitresult2$Opponent))
Splitresult3 = data.frame(Team, Opponent)
codwins = Splitresult3 %>% mutate(Win = ifelse(Team > Opponent, TRUE, FALSE), Loss = ifelse(Team < Opponent, TRUE, FALSE), Draw = ifelse(Team == Opponent, TRUE, FALSE))

COD3 = COD2 %>% mutate(Win = codwins$Win)
```

```{r}
COD3 <- COD3 %>%
  filter(GameType == "HC - TDM")

XMat <- model.matrix(TotalXP ~ Eliminations + Deaths + Damage + XPType + Win, data = COD3)[,-1]
YVec <- COD3$TotalXP

lassoModel <- glmnet(x = XMat,
                     y = YVec)
```

